### PR TITLE
Create and Publish NuGet package for XmlUnit.NET

### PR DESCRIPTION
**Pull request by joephayes**
* Add xmlunit.nuspec file
* Add init-nuget, create-nupkg, publish-nupkg and nuget targets to xmlunit.nant.build
* In init-nuget target, download nuget.exe if necessary

**N.B.** the publish-nupkg target assumes that you have saved your NuGet API Key. See [Saving your API Key with nuget.exe](http://blog.davidebbo.com/2011/03/saving-your-api-key-with-nugetexe.html)

### CODE REVIEW

**Comment by bodewig** [comment]
Thanks, I'll have to read up on nuget a bit more - I'm not even sure it is going to work on a Linux box, we'll see.

IIUC we'd use a separate nuspec for the constraints assembly.

**Comment by joephayes** [comment]
You're welcome. 

NuGet's FAQ claims that the executable runs under Mono on Linux and OSX but there are "issues" (see "Does NuGet support Mono?" at https://docs.nuget.org/consume/nuget-faq). I did also find http://headsigned.com/article/running-nuget-command-line-on-linux and https://monomvc.wordpress.com/2012/03/06/nuget-on-mono/. I hope they help.

And yes, the next step is to create additional nuspec for the constraints assembly.

Some additional TODOs (which I'm happy to work on):
* create a symbols package (https://docs.nuget.org/create/creating-and-publishing-a-symbol-package)
* adopt semantic version-ing for .NET build
* .NET framework targeting
* create a .csproj/sln file so the project can be used with IDEs like Visual Studio and SharpDevelop.

**Comment by bodewig** [comment]
I find it a bit cumbersome to discuss future directions here, maybe you'd like to join the general list? https://sourceforge.net/p/xmlunit/mailman/xmlunit-general/

I'm not particularly attached to NAnt, xbuild should work for me as well.  I'm a bit reluctant about maintaining the NAnt build next to `.csproj` as I'll likely forget to keep them in sync when new source files are added.

**Comment by joephayes** [comment]
Joined I'll send my additional comments to the list.

**Pull request merged**
