### PR TITLE
Resolve issues #4

### PR DESCRIPTION
**Pull request by joephayes**
Change nuspec authors element to "XmlUnit Contributors"
Change target framework to .NET 3.5

### CODE REVIEW

**Comment by bodewig** [comment]
We can't change the framework that way

```
Target framework could not be changed. "net-3.5" is not a valid framework identifier. Valid values are: mono-2.0, moonlight-2.0, mono-1.0, mono-4.0, mono-3.5.
```

this is the reason for the build failure on Travis as well.

**Comment by joephayes** [comment]
Ah OK - sorry about that!

J

**Comment by bodewig** [comment]
I'm not specifically targeting anything, so I'm using the mono-4.0 default.  mono-3.5 should be equivalent to net-3.5 as far as I understand.

Could you please squash your commits?

**Comment by joephayes** [comment]
Done - this pull request only resolves issue #4. Issue #7 will be dealt with separately.

**Pull request merged**
