### PR TITLE
Add support to create and publish NuGet package for xmlunit-constraints

### PR DESCRIPTION
**Pull request by joephayes**
Resolves issue #3 

Tested build on Windows 7/.NET 4.x and Ubuntu 14.04/Mono 3.2.8

### CODE REVIEW

**Comment by joephayes** [comment]
There are still issues with running nuget pack on Linux. The path separator switch works and nuget pack runs without error but no files get put into the generated nupkg. It only contains metadata.

**Comment by bodewig** [comment]
I wonder whether you should try to "fix" the XmlUnit.Core dependency in the constraints nuspec file to become `project.semantic.version`.

The problem you see on Linux sounds like http://nuget.codeplex.com/workitem/4116

Finally I thought I had upgraded to NUnit 2.6, looks as if I had forgotten to :-)

**Comment by joephayes** [comment]
Nuget pack is now working on Linux! I think the issue was NuGet issue 4116. I still needed to do the patch separator switch but it now create a nupkg with metadata and the file!

I also corrected the XmlUnit.Core dependency version in the constraints nuspec - Good catch!

For NUnit, do you want the latest (2.6.4)?

**Comment by bodewig** [comment]
Great, now if you could squash your changes ... :-)

Yes, using the latest NUnit has always been my intention, I just seem to have slipped a few updates.   I guess it could be fixes as a by-product of #11.

**Comment by joephayes** [comment]
Squashed! :-)

**Pull request merged**
