### PR TITLE
Preparing for NUnit 3: Switch from ExpectedException attribute to Ass…

### PR DESCRIPTION
**Pull request by e-tobi**
Ok, here's a new pull request with just the commit to prepare for NUnit 3 which still is compatible with NUnit2.

I'll send a separate PR with XMLUnit.NUnit3.Constraints as soon as I've done this.

### CODE REVIEW

**Comment by e-tobi** [comment]
Ok - I've updated the PR. There's now a xmlunit-nunit2-contstraints for NUnit 2.6.4.
xmlunit-contstraints now uses NUnit 3.0.1. The tests for xmlunit-contstraints and xmlunit-core are done using nunit3-console.exe. 
I tried to change as little as possible, but had to do some refactoring and linking to be able to share the tests for the nunit 2 and 3 projects.

**Comment by bodewig** [comment]
Thanks!

I may need a few days to review things, but fully intend to merge this PR before cutting alpha-03.

**Comment by e-tobi** [comment]
Great! Take your time!

**Comment by bodewig** [comment]
Thanks a lot.

I've renamed the constraints project to have NUnit 3 in its name, just to make things explicit.

**Comment by e-tobi** [comment]
Cool! And I have to thank you! Thanks to xmlunit.net all my pesky unit tests for xml output actually became readable :-)

**Pull request merged**
