### PR TITLE
Nunit3

### PR DESCRIPTION
**Pull request by e-tobi**
Here are some changes for NUnit 3.0.1 (not backwards compatible).

### CODE REVIEW

**Comment by bodewig** [comment]
NUnit 3 is pretty new and the change would break things for users of NUnit 2.x, right?

I think it would be better to provide two separate constraints assemblies.  Maybe make the constraints assembly use NUnit3 and add a new XMLUnit.NUnit2.Constraints assembly.

What do you think?

**Comment by e-tobi** [comment]
Sounds reasonable.

**Comment by bodewig** [comment]
Do you want to modify the PR?

**Comment by e-tobi** [comment]
I can do so - just give me some time, not sure if I can do it tomorrow.

**Pull request closed without merging**
